### ISSUE TITLE
Bug - Rédaction de message

### ISSUE THREAD

**Issue by JDixmier** [dinsic-pim/riot-web#261]
Parfois je suis entrain d'écrire un message et pour une raison inconnue il devient impossible d'effacer le texte, ni de déplacer la zone d'écriture. 

Par contre je peux continuer à écrire (mais seulement à la suite) et je peux envoyer le message
![Capture d’écran 2022-05-31 à 17 29 09](https://user-images.githubusercontent.com/45665538/171211722-e4affa00-1423-44d6-b280-82b6b1524053.png)

**Comment by estellecomment** [comment]
Je l'ai vu plusieurs fois aussi, Chrome v101 sur MacOS
Un refresh de la page le résoud.

Si on le revoit il faudrait essayer de se rappeler si on vient de faire une action particulière qui aurait pu le déclencher...

**Comment by odelcroi** [comment]
Same problem this morning on the 2.4.0.

> Problem gone wit' refresh


```
rageshake.js:107 Caught /sync error TypeError: Cannot read properties of undefined (reading 'highlight')
    at ne.<anonymous> (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:149785)
    at ne.s.emit (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:17:7251)
    at e.value (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:196576)
    at e.n (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:196733)
    at C.s.emit (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:17:7194)
    at C.addReceipt (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:239007)
    at C.addEphemeralEvents (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:237035)
    at https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:74:29782
    at g (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:24:65239)
    at Generator._invoke (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:24:64992)
    at Generator.forEach.e.<computed> [as next] (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:24:65419)
    at Generator.c (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:6:75928)
    at p._promiseFulfilled (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:6:32186)
    at https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:6:34213
From previous event:
    at O.G [as _captureStackTrace] (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:6:18128)
    at ne.<anonymous> (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:6:37708)
    at ne.startClient (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:190216)
    at e.<anonymous> (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:10020)
    at g (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:1238335)
    at Generator._invoke (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:1238088)
    at Generator.forEach.e.<computed> [as next] (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:55:1238515)
    at Generator.c (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:143385)
    at p._promiseFulfilled (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:99643)
    at O._settlePromise (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:117308)
    at O._settlePromise0 (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:117906)
    at O._settlePromises (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:119258)
    at u (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:70552)
    at l (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:70491)
    at s._drainQueues (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:71605)
    at drainQueues (https://www.tchap.gouv.fr/bundles/fd88e23aac8790b6be81/bundle.js:1:70425)
```

and... 


```
Error: Error decrypting prekey message with existing session id lxJ+xZvqxo/MeiVj4IwRdUR3Bw1yzkVvqxtksHLEhzc: OLM.BAD_MESSAGE_MAC]
forEach.e.<computed> @ rageshake.js:107
```
..
```
rageshake.js:107 Error decrypting event (id=$165469338443446mleDF:agent.dinum.tchap.gouv.fr): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: 4FJvIndWqyNsOKqe3b7yOHDfUT8iOCow217aFcGXr3o|V6SZcEwD+NvVKSKgwJpK7T6wdbMEkFDCbQlhYpDScms]
forEach.e.<computed> @ rageshake.js:107
```
...
can not share the whole log file, too many identifiers..
